name: Integrate Pipeline Web with Test Routine and Deployment in Cloud Provider

on:
  push:

env:
  API_DOMAIN: nest-app
  FRONT_DOMAIN: next-app-tawny.vercel.app
  MAIN_BRANCH: main

jobs:
  # test-routine:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [12.x]

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}

  deployment-step:
    runs-on: ubuntu-latest
    # needs: test-routine

    steps:
      - name: Checkout (frontend - matching branch)
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set tag var
        id: vars
        run: |
          echo ::set-output name=API_APP_NAME::`echo '${{ env.API_DOMAIN }}-${{ env.GITHUB_REF_NAME_SLUG }}' | head -c 30`
          echo ::set-output name=FRONT_APP_NAME::`echo '${{ env.GITHUB_REF_NAME_SLUG }}-${{ env.FRONT_DOMAIN }}'`

        # Branching Deploy
      - name: Test URLS
        run: |
          echo "API URL : https://${{ steps.vars.outputs.API_APP_NAME }}.herokuapp.com"
          echo "FRONT URL :https://${{ steps.vars.outputs.FRONT_APP_NAME }}"

      # - name: Extract branch name
      #   shell: bash
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch

      # - run: |
      #     curl -XPOST -u "${{ secrets.GIT_USERNAME}}:${{secrets.GIT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${{secrets.GIT_USERNAME}}/biscott-api/dispatches --data '{"event_type": "build_application", "client_payload": {"branch": "${{ steps.extract_branch.outputs.branch }}}", "url": "${{ env.GITHUB_REF_SLUG }}"}}'

      # Branching Deploy
      - name: Branching Deploy
        uses: amondnet/vercel-action@v20
        id: vercel-deploy-branching
        with:
          vercel-token: "cv339XaVihlWc9D7S5s0ojQQ"

          vercel-org-id: "W7Xp2ctxgvqN96MKAN2bpyMH"
          vercel-project-id: "prj_pPEbxN5JQZAsV1aVCOPxh3KkmgnC"
          scope: "ggggggg"
          alias-domains: |
            ${{ steps.vars.outputs.FRONT_APP_NAME }}

      # Branching Deploy
      - name: Branching Deploy URLS
        run: |
          echo "API URL : https://${{ steps.vars.outputs.API_APP_NAME  }}.herokuapp.com"
          echo "FRONT URL :https://${{ steps.vars.outputs.FRONT_APP_NAME }}"
