name: Integrate Pipeline Web with Test Routine and Deployment in Cloud Provider

on:
  push:

env:
  API_DOMAIN: nest-app
  FRONT_DOMAIN: next-app-tawny.vercel.app
  MAIN_BRANCH: main

jobs:
  # test-routine:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [12.x]

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}

  deployment-step:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    # needs: test-routine

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Deployed URL
        run: echo "NOT CLOSED"

      # - name: Set tag var
      #   id: vars
      #   run: |
      #     echo ::set-output name=FRONT_APP_NAME::`echo '${{ env.GITHUB_REF_NAME_SLUG }}-${{ env.FRONT_DOMAIN }}'`

      # # - name: Extract branch name
      # #   shell: bash
      # #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      # #   id: extract_branch
      - name: Deployed URL
        run: echo "API URL:https://test2.herokuapp.com"

      - name: Deployed URL
        run: echo "API URL:https://${{ github.event.action }}.herokuapp.com"

      - name: Inject hello
        run: echo "API URL:${{ github.event.action }}"

      - run: curl -X POST -u "Authorization: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" -H "Accept:application/vnd.github.v3+json" -H "Content-Type:application/json" https://api.github.com/repos/anasmebarki1996-c4t/nest-app/dispatches --ref develop --data '{"event_type":"build_application","client_payload":{"branch":"test", "url":"gggg","github_event_action":"${{ github.event.action }}"}}'

      # # Branching Deploy
      # - name: Branching Deploy
      #   uses: amondnet/vercel-action@v20
      #   id: vercel-deploy-branching
      #   with:
      #     vercel-token: "cv339XaVihlWc9D7S5s0ojQQ"
      #     vercel-args: "--build-env NEXT_PUBLIC_API_BASE_URL=herokuapp.com/v1"
      #     vercel-org-id: "team_XS84nBwfHog9694hSuWI8Ume"
      #     vercel-project-id: "prj_pPEbxN5JQZAsV1aVCOPxh3KkmgnC"
      #     scope: "ggggggg"
      #     alias-domains: |
      #       ${{ steps.vars.outputs.FRONT_APP_NAME }}

      # # Branching Deploy
      # - name: Branching Deploy URLS
      #   run: |
      #     echo "FRONT URL :https://${{ steps.vars.outputs.FRONT_APP_NAME }}"

  destroy-step:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Deployed URL
        run: echo "CLOSED"

      - run: curl -X POST -u "Authorization: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" -H "Accept:application/vnd.github.v3+json" -H "Content-Type:application/json" https://api.github.com/repos/anasmebarki1996-c4t/nest-app/dispatches --ref develop --data '{"event_type":"build_application","client_payload":{"branch":"test", "url":"gggg","github_event_action":"${{ github.event.action }}"}}'
