name: Pipeline Web with Test Routine and Deployment in Cloud Provider 🦾🤖🦾

on:
  push:

jobs:
  test-routine:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

  deployment-step:
    runs-on: ubuntu-latest
    needs: test-routine

    steps:
      - name: Checkout (frontend - matching branch)
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # - name: Checkout (frontend - matching branch)
      #   uses: actions/checkout@v2
      #   ref: feature/add

      - run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${{secrets.PAT_USERNAME}}/${{ env.APPLICATION_NAME }}/dispatches --data '{"event_type": "build_application", "client_payload": {"branch": "${{steps.extract_branch.outputs.branch}}}"} }'

      # - name: Checkout (frontend - master)
      #   if: steps.checkout-matching-branch.outputs.failure == 'true'
      #   uses: actions/checkout@v2
      #   with:
      #     ref: master

      # - name: Inject slug/short variables
      #   uses: rlespinasse/github-slug-action@v3.x

      # Production Deploy
      # - name: Production Deploy
      #   uses: amondnet/vercel-action@v20
      #   id: vercel-deploy-production
      #   if: github.ref == 'refs/heads/main'
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-args: "--prod --build-env NEXT_PUBLIC_API_BASE_URL=https://${{ env.GITHUB_REPOSITORY_SLUG }}-${{ env.GITHUB_REF_SLUG }}.herokuapp.com"
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      # # Branching Deploy
      # - name: Branching Deploy
      #   uses: amondnet/vercel-action@v20
      #   id: vercel-deploy-branching
      #   if: github.ref != 'refs/heads/main'
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-args: "--build-env NEXT_PUBLIC_API_BASE_URL=https://${{ env.GITHUB_REPOSITORY_SLUG }}-${{ env.GITHUB_REF_SLUG }}.herokuapp.com"
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
